import random

TICK = 100

SNAKE_BODY_COLOR = 'green'
SNAKE_HEAD_COLOR = 'lime green'

BACKGROUND_COLOR = 'black'
FOOD_COLOR = 'red'

GRID_WIDTH_IN_SQMS = 20
GRID_HEIGHT_IN_SQMS = 20
GRID_SQM_SIZE = 30

SCREEN_TITLE = 'Snake Game'

# Starting Screen:
'Text'
PLAY_BUTTON_TEXT_COORDINATES = 100,200
PLAY_BUTTON_TEXT = 'Start Game'
PLAY_BUTTON_TEXT_COLOR = 'gray60'
PLAY_BUTTON_TEXT_SIZE = 50
PLAY_BUTTON_TEXT_FONT = 'verdana'
PLAY_BUTTON_TEXT_ANCHOR = 'nw'

AI_BUTTON_TEXT_COORDINATES = 150,300
AI_BUTTON_TEXT = 'AI Mode'


# AI Configurations
WATCHING_TICK = 0.01
AI_TICK = 0.0
# MUTATION_RATE = random.randint(20,500)/100
MUTATION_THRESHOLD = 48
LIFE_SPAN = 40
POPULATION_SIZE = 120
